### ISSUE TITLE
Ignore node_modules with a .gitignore file 

### ISSUE THREAD

**Issue by doriel** [ichtrojan/node-redis#4]
Create a ".gitignore" file and add -> node_modules to ignore the modules, they don't have to be a part of the Repo

**Comment by ichtrojan** [comment]
You could send in a PR, I'm not close to my laptop

**Comment by doriel** [comment]
@ichtrojan i am on it.

**Comment by doriel** [comment]
Done

**Comment by ichtrojan** [comment]
Merged👏🏽
